# -*- coding: utf-8 -*-
"""Entrega1_POO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFq1vHtZX3nDvbF55CwcYKwA5zv3ET8c
"""

class Edades:
  @staticmethod
  def calcular_edalber(edjuan):
    return (2*edjuan)/3

  @staticmethod
  def calcular_edana(edjuan):
    return (4*edjuan)/3

  @staticmethod
  def calcular_edmama(edjuan):
    return edjuan + edalber + edana

edjuan = 9
edalber = Edades.calcular_edalber(edjuan)
edana = Edades.calcular_edana(edjuan)
edmama = Edades.calcular_edmama(edjuan)

print("Las edades son: \nAlberto =", edalber, "\nJuan =", edjuan, "\nAna =", edana, "\nMamá = ", edmama)

import math

#Variables
suma = 0
x    = 20
y    = 40

#Calculos
suma = suma + x
x = x + math.pow(y,2)
suma = suma + (x/y)

print("El valor final de la suma es: ",suma)

class Nomina:

  @staticmethod
  def calc_salario_bruto(horas_trabajadas, valor_hora):
    return horas_trabajadas * valor_hora

  @staticmethod
  def calc_valor_retefuente(porcentaje_retefuente, salario_bruto):
    return porcentaje_retefuente * salario_bruto

  @staticmethod
  def calc_salario_neto(salario_bruto, valor_retefuente):
    return salario_bruto - valor_retefuente

#Variables
horas_trabajadas      = 48
valor_hora            = 5000
retencion             = 12.5
porcentaje_retefuente = retencion / 100

#Calculos
salario_bruto = Nomina.calc_salario_bruto(horas_trabajadas, valor_hora)
valor_retefuente = Nomina.calc_valor_retefuente(porcentaje_retefuente, salario_bruto)
salario_neto = Nomina.calc_salario_neto(salario_bruto, valor_retefuente)

print("El salario bruto es:", salario_bruto)
print("El valor de la retención es:", valor_retefuente)
print("El salario neto es:", salario_neto)

import math

class Calculos:

  @staticmethod
  def calc_cuadrado(numero):
    return math.pow(numero, 2)

  @staticmethod
  def calc_cubo(numero):
    return math.pow(numero, 3)

 #Varible y calculos
numero = 4

cuadrado = Calculos.calc_cuadrado(numero)
cubo = Calculos.calc_cubo(numero)

print("El cuadrado de", numero, "es:", cuadrado)
print("El cubo de", numero, "es:", cubo)

import math

class Calculos:

  @staticmethod
  def cal_longitud_circ(radio):
    return 2*math.pi*radio

  @staticmethod
  def cal_area_circ(radio):
    return math.pi*math.pow(radio, 2)

radio = 3

longitud_circ = Calculos.cal_longitud_circ(radio)
area_circ = Calculos.cal_area_circ(radio)

print("La longitud de la circunferencia es:", longitud_circ)
print("El área de la circunferencia es:", area_circ)