# -*- coding: utf-8 -*-
"""2_5_POO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYKZQ1dzdGhXvmqI_pjmL9AaiOHYlc_Q
"""

class CuentaBancaria:

    def __init__(self, nombres_titular, apellidos_titular, numero_cuenta, tipo_cuenta):

        #Constructor de la clase CuentaBancaria
        self.nombres_titular = nombres_titular
        self.apellidos_titular = apellidos_titular
        self.numero_cuenta = numero_cuenta
        self.tipo_cuenta = tipo_cuenta
        self.saldo = 0

    def imprimir(self):
        #Datos cuenta
        print("\nDatos Cuenta Bancaria")
        print("Nombres del titular:", self.nombres_titular)
        print("Apellidos del titular:", self.apellidos_titular)
        print("Número de cuenta:", self.numero_cuenta)
        print("Tipo de cuenta:", self.tipo_cuenta)
        print("Saldo: $", self.saldo)


    def consultar_saldo(self):
      print(f"\nEl saldo actual es: ${self.saldo:,.2f}")

    def consignar(self, valor):

          if valor > 0:
              self.saldo += valor
              print("Se ha consignado: $", valor, "en la cuenta.")
              print(f"El nuevo saldo es: $",self.saldo)
              return True
          else:
              print("El valor a consignar debe ser mayor que cero.")
              return False

    def retirar(self, valor):

        if valor > 0 and valor <= self.saldo:
            self.saldo -= valor
            print(" Se ha retirado $", valor, "de la cuenta.")
            print("El nuevo saldo es: $", self.saldo)
            return True
        elif valor <= 0:
            print("El valor a retirar debe ser mayor que cero.")
            return False
        else:
            print("No se puede retirar $", valor, "Saldo insuficiente.")
            print("Saldo actual: $", self.saldo)
            return False


# Solicitar datos al usuario
print("CREAR CUENTA")
nombres = input("Ingrese los nombres del titular: ")
apellidos = input("Ingrese los apellidos del titular: ")

# Validar que el número de cuenta sea un número entero
while True:
    try:
        numero_cuenta = int(input("Ingrese el número de cuenta: "))
        break
    except ValueError:
        print("Ingrese un número válido.")

# Seleccionar tipo de cuenta
print("\nSeleccione su tipo de cuenta:")
print("1. Ahorros")
print("2. Corriente")

while True:
    try:
        opcion_tipo = int(input("Seleccione el tipo de cuenta: "))
        if opcion_tipo == 1:
            tipo_cuenta = "Ahorros"
            break
        elif opcion_tipo == 2:
            tipo_cuenta = "Corriente"
            break
        else:
            print("Opción no válida.")
    except ValueError:
        print("Ingrese un número válido.")


# Crear la cuenta bancaria
cuenta = CuentaBancaria(nombres, apellidos, numero_cuenta, tipo_cuenta)

# Mostrar los datos de la cuenta creada
cuenta.imprimir()


while True:
    print("\n1. Consultar saldo")
    print("2. Consignar dinero")
    print("3. Retirar dinero")
    print("4. Mostrar datos de la cuenta")
    print("5. Salir")

    opcion = input("\nSeleccione una opción: ")

    if opcion == "1":
        cuenta.consultar_saldo()

    elif opcion == "2":
        try:
            valor = float(input("Ingrese el valor a consignar: $"))
            cuenta.consignar(valor)
        except ValueError:
            print("Debe ingresar un valor numérico válido.")

    elif opcion == "3":
        try:
            valor = float(input("Ingrese el valor a retirar: $"))
            cuenta.retirar(valor)
        except ValueError:
            print("Debe ingresar un valor numérico válido.")

    elif opcion == "4":
        cuenta.imprimir()

    elif opcion == "5":
        print("Finalizado")
        break

    else:
        print("Opción no válida.")