# -*- coding: utf-8 -*-
"""Ejercicio_17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJOxEs8qv28cZSg6QoSxVTfQ0BlzGNlT
"""

import math

class Calculos:

  @staticmethod
  def cal_longitud_circ(radio):
    return 2*math.pi*radio

  @staticmethod
  def cal_area_circ(radio):
    return math.pi*math.pow(radio, 2)

radio = 3

longitud_circ = Calculos.cal_longitud_circ(radio)
area_circ = Calculos.cal_area_circ(radio)

print("La longitud de la circunferencia es:", longitud_circ)
print("El área de la circunferencia es:", area_circ)