# -*- coding: utf-8 -*-
"""Ejercicio_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xkJ-FucS-O0g3z1DXiMsjJIDPat7hP-2
"""

import math

#Variables
suma = 0
x    = 20
y    = 40

#Calculos
suma = suma + x
x = x + math.pow(y,2)
suma = suma + (x/y)

print("El valor final de la suma es: ",suma)