# -*- coding: utf-8 -*-
"""Ejercicio_14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggGW91WT1kcPNVRQkRxskvMrTD2PkdpU
"""

import math

class Calculos:

  @staticmethod
  def calc_cuadrado(numero):
    return math.pow(numero, 2)

  @staticmethod
  def calc_cubo(numero):
    return math.pow(numero, 3)

 #Varible y calculos
numero = 4

cuadrado = Calculos.calc_cuadrado(numero)
cubo = Calculos.calc_cubo(numero)

print("El cuadrado de", numero, "es:", cuadrado)
print("El cubo de", numero, "es:", cubo)