# -*- coding: utf-8 -*-
"""Ejercicio_12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4NgOP9tL2iqvcmo7QiDm0yaOPmR50yw
"""

class Nomina:

  @staticmethod
  def calc_salario_bruto(horas_trabajadas, valor_hora):
    return horas_trabajadas * valor_hora

  @staticmethod
  def calc_valor_retefuente(porcentaje_retefuente, salario_bruto):
    return porcentaje_retefuente * salario_bruto

  @staticmethod
  def calc_salario_neto(salario_bruto, valor_retefuente):
    return salario_bruto - valor_retefuente

#Variables
horas_trabajadas      = 48
valor_hora            = 5000
retencion             = 12.5
porcentaje_retefuente = retencion / 100

#Calculos
salario_bruto = Nomina.calc_salario_bruto(horas_trabajadas, valor_hora)
valor_retefuente = Nomina.calc_valor_retefuente(porcentaje_retefuente, salario_bruto)
salario_neto = Nomina.calc_salario_neto(salario_bruto, valor_retefuente)

print("El salario bruto es:", salario_bruto)
print("El valor de la retención es:", valor_retefuente)
print("El salario neto es:", salario_neto)