# -*- coding: utf-8 -*-
"""Entrega_1_Ej_4ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFq1vHtZX3nDvbF55CwcYKwA5zv3ET8c
"""

class Edades:
  @staticmethod
  def calcular_edalber(edjuan):
    return (2*edjuan)/3

  @staticmethod
  def calcular_edana(edjuan):
    return (4*edjuan)/3

  @staticmethod
  def calcular_edmama(edjuan):
    return edjuan + edalber + edana

edjuan = 9
edalber = Edades.calcular_edalber(edjuan)
edana = Edades.calcular_edana(edjuan)
edmama = Edades.calcular_edmama(edjuan)

print("Las edades son: \nAlberto =", edalber, "\nJuan =", edjuan, "\nAna =", edana, "\nMamá = ", edmama)